import { Region } from '../../../../ngx-mitaa.interfaces';

export const mwanza: Region = {
  region: 'Mwanza',
  districts: [
    {
      district: 'Nyamagana',
      wards: [
        {
          ward: 'Nyamagana',
          streets: [
            'Capripoint',
            'Nyamagana Mashariki',
            'Nyamagana Magharibi',
            'Idara Ya Maji',
          ],
        },
        {
          ward: 'Pamba',
          streets: [
            'Pamba  A',
            'Pamba  B',
            'Miembeni  A',
            'Miembeni  B',
            'Bugarika  Kusini',
            'Bugarika  Kaskazini',
            'Mission',
            'Mlimani',
            'Zahanati',
            'Jeshini',
          ],
        },
        {
          ward: 'Mirongo',
          streets: ['Rufiji', 'Uhuru', 'Utemini'],
        },
        {
          ward: 'Isamilo',
          streets: [
            'Nyakabungo  A',
            'Nyakabungo  C',
            'Nyakabungo',
            'Nera',
            'Isamilo  Kaskazini   A',
            'Isamilo  Kaskazini   B',
            'S.d.a',
            'Nyakabungo B',
            'Lake',
            'National',
            'Msikiti',
          ],
        },
        {
          ward: 'Mbugani',
          streets: [
            'Unguja',
            'Nyashana',
            'Mbugani A',
            'Mbugani B',
            'Kasulu',
            'Uhuru',
          ],
        },
        {
          ward: 'Igogo',
          streets: [
            'Igogo Kaskazini  A',
            'Kambarage',
            'Minja',
            'Bugando',
            'Jiwe',
            'Mulungushi',
            'Kwimba',
            'Azimio',
            'Mwenge',
            'Malulu',
          ],
        },
        {
          ward: 'Mkuyuni',
          streets: [
            'Mkuyuni Sokoni',
            'Relwe',
            'Shede',
            "Kang'anga",
            'Mulumbani',
            'Mahina Relini',
            'Mahakama',
            'Nyakurunduma',
          ],
        },
        {
          ward: 'Mabatini',
          streets: [
            'Mission',
            'Majengo Mapya',
            'Nyerere A',
            'Nyerere B',
            'Mabatini Kusini',
            'Mabatini Kaskazini',
          ],
        },
        {
          ward: 'Mkolani',
          streets: [
            "Nyang'hingi",
            'Utemini',
            'Ibanda',
            'Majengo',
            'Mkolani',
            'Nyamazobe',
            'Kasese',
            'Buganda',
            'Nyamalango',
            'Nyanza',
          ],
        },
        {
          ward: 'Luchelele',
          streets: [
            'Silivini',
            'Kasamiko',
            'Nganza',
            'Nyakalekwa',
            'Sweya',
            'Kisoko',
            'Malimbe',
            'Luchelele Ziwani',
            'Ihumilo',
            'Shadi',
          ],
        },
        {
          ward: 'Buhongwa',
          streets: [
            'Buhongwa Mashariki',
            'Buhongwa Magharibi',
            'Sahwa',
            'Bulale',
            'Bugayamba',
            'Nyakagwa',
            'Semba',
            'Nyambiti',
            "Ng'wanhalanga",
            'Buguku',
            'Isebanda',
            "Ng'washi",
            'Igwambiti',
            'Ihyila',
            'Nyaluhama',
            'Mitimirefu',
            'Nyanembe',
            'Nyangwi',
            'Kigoto',
            'Kishira',
            'Nyamatara',
            'Ihyila B',
            'Shibayi',
          ],
        },
        {
          ward: 'Lwanhima',
          streets: [
            'Nyakamanga',
            'Kageye',
            'Kagera',
            'Igwambiti B',
            'Igwambiti D',
            'Ihushi',
            'Igwambiti C',
            'Mwalukila',
            'Nhobola',
            'Nyabahigi',
            'Isabenda',
            'Igwambiti',
            'Semba',
            'Bugayamba',
            'Sahwa',
            'Maliza',
            'Lwanhima Magharibi',
            'Kibundubundu',
          ],
        },
        {
          ward: 'Butimba',
          streets: [
            'Tambukareli',
            'Kambarage',
            'Ziwa',
            'Amani',
            'Iseni',
            'Bohari',
            'Hospitali',
            'Kanyerere',
          ],
        },
        {
          ward: 'Nyegezi',
          streets: [
            'Swila',
            'Nkamba',
            'Califonia',
            'Kuzenza',
            'Nyabulogoya',
            'Nchenga',
            'Igubinya',
            'Ibanda',
          ],
        },
        {
          ward: 'Igoma',
          streets: [
            'Igoma Mashariki',
            'Igoma Kati',
            'Mwembeni',
            'Shamaliwa A',
            'Kishili A',
            'Ndofe',
            'Kikwete',
            'Bukaga',
            'Kanenwa',
            'Fumangila Mashariki',
            'Mandela',
            'Nyerere',
            'Mbugani',
            'Ihushi',
          ],
        },
        {
          ward: 'Kishili',
          streets: [
            'Mtakuja',
            'Kilimo A',
            'Kilimo B',
            'Shamaliwa B',
            'Kishili B',
            'Dokta Shein',
            'Kakebe',
            'Mkapa',
            'Fumangila Magharibi',
            'Kanindo',
            'Igoma Magharibi A',
            'Igoma Magharibi B',
          ],
        },
        {
          ward: 'Mahina',
          streets: [
            'Bugarika',
            'Mahina Kati',
            'Mwananchi',
            'Mahina',
            'Nyangulugulu',
            'Kagomu',
            'Ipuli',
            'Igelegele',
            'Suzuni',
          ],
        },
        {
          ward: 'Mhandu',
          streets: [
            'Kasota',
            'Sokoni',
            'Kisiwani',
            'Shigunga',
            'Mahango',
            'Temeke',
            'Maswa Mashariki',
            'Maswa Magharibi',
            'Mhandu',
            "Isengeng'he A",
            "Isengeng'he B",
          ],
        },
      ],
    },
    {
      district: 'Ilemela',
      wards: [
        {
          ward: 'Nyakato',
          streets: [
            'Nhc Mashariki',
            'Nhc Magharibi',
            'Nhc',
            'Ihangilo',
            'Gedeli',
            'Majengo Mapya',
            'Kangaye A',
            'Kangaye B',
          ],
        },
        {
          ward: 'Buswelu',
          streets: [
            'Bujingwa',
            'Buswelu A',
            'Buswelu B',
            'Buhyila',
            'Bulola A',
            'Bulola B',
            'Busenga',
            'Zembwela',
            'Bulola Mlimani',
            'Majengo Mapya',
            'Kigala',
          ],
        },
        {
          ward: 'Ilemela',
          streets: [
            'Ilemela',
            'Balyeheye',
            'Nyangungulu',
            'Bukengwa',
            'Kahasa',
            'Mwambani',
            'Butuja',
            'Sabasaba',
            'Madukulu',
          ],
        },
        {
          ward: 'Pasiansi',
          streets: [
            'Pasiansi Juu',
            'Pasiansi Magharibi',
            'Bwiru Ziwani',
            'Bwiru Mchangani',
            'Pasiansi Chini',
            'Bwiu Elimu',
            'Bwiru Press',
            'Bwiru Bima',
          ],
        },
        {
          ward: 'Bugogwa',
          streets: [
            'Igombe A',
            'Bugogwa',
            'Lugezi',
            'Kabangaja',
            'Kasamwa',
            'Igombe B',
            'Kigote',
            'Kilabela',
            'Bujimwa',
            'Kayenze Ndogo',
            'Kisundi',
            'Isanzu',
            'Igogwe',
            'Nkoroto',
            'Kilimanilwe Mtemi',
          ],
        },
        {
          ward: 'Sangabuye',
          streets: [
            'Isesa',
            'Sangabuye',
            'Nyafula',
            'Kabusungu',
            'Nyashimba',
            'Lugeye',
            'Nyamiswi',
            "Mg'wang'wila",
            'Ilekako',
            'Ihalalo',
            'Igalagala',
            "Imalang'ombe",
            'Lwashi',
            'Igumamoyo',
          ],
        },
        {
          ward: 'Mecco',
          streets: [
            'Mecco Mashariki',
            'Mecco Kaskazini',
            'Mecco Kusini',
            'Nundu',
            'Gedeli Kivukoni',
          ],
        },
        {
          ward: 'Buzuruga',
          streets: [
            'Buzuruga Kaskazini',
            'Buzuruga Kusini',
            'Nyambiti',
            'Ustawi',
            'Buzuruga Mashariki',
          ],
        },
        {
          ward: 'Nyasaka',
          streets: [
            'Kiloleli B',
            'Chamwenda',
            'Nyasaka',
            'Nyasaka Senta',
            'Nyamhuge',
            'Nyanda',
          ],
        },
        {
          ward: 'Kahama',
          streets: [
            'Buduku',
            'Buyombe',
            'Lukobe',
            'Butega',
            'Isela',
            'Kahama',
            'Magaka',
            'Kadinda',
            'Wiluhnya',
          ],
        },
        {
          ward: 'Kiseke',
          streets: [
            'Kibambo',
            'Kiseke',
            'Green View',
            'Isenga',
            'P.p.f',
            'Nyabusalu',
            'Nsumba',
            'Zenze',
          ],
        },
        {
          ward: 'Kayenze',
          streets: ['Kayenze', 'Bezi', 'Lutongo', 'Iponyabugale', 'Iseni'],
        },
        {
          ward: 'Shibula',
          streets: [
            'Semba A',
            'Semba B',
            'Buganda',
            'Mhonze A',
            'Mhonze B',
            'Nyamwilolelwa',
            'Kihiri',
            'Shibula',
            'Bulyang’hulu',
            'Ibaya',
            'Butindo',
            'Ilaila',
            'Chabakima',
            'Masemele',
          ],
        },
        {
          ward: 'Kawekamo',
          streets: [
            'Nyasaka A',
            'Nyasaka B',
            'Nyasaka C',
            'Msumbiji',
            'Kawekamo B',
            'Pasiansi Mashariki A',
            'Pasiansi Mashariki B',
          ],
        },
        {
          ward: 'Kitangiri',
          streets: [
            'Jiwe Kuu',
            'Kitangiri Kati',
            'Kitangiri A',
            'Kitangiri B',
            'Medical Research',
            'Mihama',
            'Kileleni',
            'Mwinuko',
          ],
        },
        {
          ward: 'Kirumba',
          streets: [
            'Kirumba Kati',
            'Ngara',
            'Kabohoro',
            'Ibanda Juu',
            'Ibanda Ziwani',
            'Mlimani',
            'Kigoto',
            'Ibanda Busisi',
            'Kabuhoro B',
            'Kiyungi',
            'Magomeni',
            'Mlimani B',
          ],
        },
        {
          ward: 'Nyamanoro',
          streets: [
            'Kilimahewa A',
            'Nyamanoro A',
            'Nyamanoro Mashariki',
            'Kilimahewa B',
            'Mkudi',
            'Nenetwa',
            'Myampala',
          ],
        },
        {
          ward: 'Ibungilo',
          streets: [
            'Ibungilo A',
            'Ibungilo B',
            'Nyamanoro Kaskazini',
            'Nyamanoro C',
            'Kiloleli A',
            'Kiloleli B',
            'Nyamanoro B',
          ],
        },
        {
          ward: 'Nyamhongolo',
          streets: [
            'Nyamadoke',
            'Ibinza',
            'Ikigijo',
            'Lwenyashinga',
            'Nyamhongolo',
            'Bupumla',
            'Kashishi',
            'Ilamba A',
            'Ilamba B',
            'Kagihwa',
            'Mtakuja',
            'Busimile',
          ],
        },
      ],
    },
    {
      district: 'Sengerema',
      wards: [
        {
          ward: 'Ibisabageni',
          streets: [
            'Sekondari Road',
            'Mjini Kati',
            'Ibisabageni',
            'Busisi Road',
            'Bukara',
          ],
        },
        {
          ward: 'Nyatukara',
          streets: [
            'Bomani',
            'Kisima Cha Chumvi',
            'Geita Road',
            'Nyatukala',
            "Isung'ang'olo",
          ],
        },
        {
          ward: 'Nyampulukano',
          streets: ['Igogo', 'Migombani', 'Mnadani'],
        },
        {
          ward: 'Mwabaluhi',
          streets: [
            "Isung'ang'holo",
            'Ofisini',
            'Kilabela',
            'Kanyamwanza',
            'Balatogwa',
          ],
        },
        {
          ward: 'Kafunzo',
          streets: ['Kafunzo', 'Bilulumo', 'Luhorongoma'],
        },
        {
          ward: 'Bupandwa',
          streets: ['Bupandwamhela', 'Itulabusiga', 'Chema', 'Mnazi Mmoja'],
        },
        {
          ward: 'Katwe',
          streets: ['Katwe', 'Kahunda'],
        },
        {
          ward: 'Kalebezo',
          streets: [
            'Magulukenda',
            'Nyashana',
            'Katoma',
            'Busekeseke',
            'Kalebezo',
          ],
        },
        {
          ward: 'Nyehunge',
          streets: ['Nyamadoke', 'Isaka', 'Nyehunge', 'Mwabasabi', 'Kayenze'],
        },
        {
          ward: 'Maisome',
          streets: ['Kisaba', 'Kanoni', 'Busikimbi'],
        },
        {
          ward: 'Nyakasasa',
          streets: ['Nyakasasa'],
        },
        {
          ward: 'Lugata',
          streets: [
            'Nyakabanga',
            'Lugata',
            'Izindabo',
            'Nyonga',
            'Kabaganga',
            'Mgogo',
          ],
        },
        {
          ward: 'Nyakaliro',
          streets: ['Nyakaliro', 'Lumeya', 'Kasela', 'Itumbili'],
        },
        {
          ward: 'Nyakasungwa',
          streets: ['Nyakasungwa', 'Majengo'],
        },
        {
          ward: 'Kazunzu',
          streets: ['Kakobe', 'Nyambeba', 'Kasalaji', 'Ilyamchele'],
        },
        {
          ward: 'Nyanzenda',
          streets: ['Nyamabano', 'Nyanzenda', 'Migukulama'],
        },
      ],
    },
    {
      district: 'Magu',
      wards: [
        {
          ward: 'Nkungulu',
          streets: ['Kayenze "b"'],
        },
        {
          ward: 'Shishani',
          streets: ['Isolo', 'Shishani', 'Mahaha'],
        },
        {
          ward: 'Lubugu',
          streets: ['Bubinza', 'Kisamba', 'Sayaka', 'Lubugu', 'Nsolla'],
        },
        {
          ward: 'Kandawe',
          streets: ['Sagani', 'Ng’watelesha', 'Kipeja', 'Ihimbili'],
        },
        {
          ward: 'Buhumbi',
          streets: [
            'Buhumbi',
            'Mwamibanga',
            'Kitongo',
            'Nyashoshi',
            'Misungwi',
          ],
        },
        {
          ward: 'Bujora',
          streets: ["Kisesa 'a'", 'Bujora', 'Kanyama'],
        },
        {
          ward: 'Bukandwe',
          streets: ['Isangijo', 'Welamasonga', 'Ihayabuyaga'],
        },
        {
          ward: 'Chabula',
          streets: ['Chabula', 'Bugando', 'Nyashigwe'],
        },
        {
          ward: 'Kabila',
          streets: ['Kabila', 'Mwamagoli', 'Igombe', 'Ndagalu'],
        },
        {
          ward: 'Jinjimili',
          streets: ['Jinjimili', 'Kabale', 'Nyasato'],
        },
        {
          ward: 'Itumbili',
          streets: ['Nyasato'],
        },
        {
          ward: 'Isandula',
          streets: ['Nyasato'],
        },
      ],
    },
    {
      district: 'Misungwi',
      wards: [
        {
          ward: 'Nhundulu',
          streets: ['Mwagiligili'],
        },
        {
          ward: 'Mamaye',
          streets: ['Ibongoya "b"', 'Mwalwigi', 'Magaka'],
        },
        {
          ward: 'Mondo',
          streets: ['Mondo', 'Ntulya'],
        },
        {
          ward: 'Fella',
          streets: ['Fella', 'Ngeleka', 'Bujingwa'],
        },
      ],
    },
  ],
};
