import { Region } from '../../../../ngx-mitaa.interfaces';

export const darEsSalaam: Region = {
  region: 'Dar es Salaam',
  districts: [
    {
      district: 'Ilala Cbd',
      wards: [
        {
          ward: 'Kivukoni',
          streets: ['Kivukoni', 'Sea View'],
        },
        {
          ward: 'Upanga Mashariki',
          streets: ['Kitonga', 'Kibasila'],
        },
        {
          ward: 'Upanga Magharibi',
          streets: ['Fire', 'Charambe', 'Mfaume'],
        },
        {
          ward: 'Kisutu',
          streets: ['Kisutu', 'Mtendeni'],
        },
        {
          ward: 'Mchafukoge',
          streets: ['Kitumbini', 'Mchafukoge'],
        },
        {
          ward: 'Kariakoo',
          streets: [
            'Kariakoo Magharibi',
            'Kariakoo Kaskazini',
            'Kariakoo Mashariki',
          ],
        },
        {
          ward: 'Gerezani',
          streets: ['Gerezani Mashariki', 'Gerezani Magharibi'],
        },
        {
          ward: 'Jangwani',
          streets: ['Ukombozi', 'Mnazi Mmoja', 'Mtambani A', 'Mtambani B'],
        },
        {
          ward: 'Mchikichini',
          streets: ['Mission Quarter', 'Ilala Kota', 'Msimbazi Bondeni'],
        },
      ],
    },
    {
      district: 'Ilala',
      wards: [
        {
          ward: 'Ilala',
          streets: ['Mafuriko', 'Kasulu', 'Karume', 'Shariff Shamba', 'Amana'],
        },
        {
          ward: 'Buguruni',
          streets: ['Malapa', 'Madenge', 'Kisiwani', 'Mvinjeni'],
        },
        {
          ward: 'Tabata',
          streets: [
            'Mandela',
            'Tabata',
            'Matumbi',
            'Msimbazi',
            'Kisiwani',
            'Tenge',
            'Mtambani',
            'Msimbazi Magharibi',
          ],
        },
        {
          ward: 'Kimanga',
          streets: [
            'Tembomgwaza',
            'Kimanga',
            'Kimanga Darajani',
            'Banebane',
            'Kihimbwa',
            'Sokoine',
            'Twiga',
          ],
        },
        {
          ward: 'Segerea',
          streets: ['Mgombani', 'Ugombolwa', 'Segerea', 'Mfaume'],
        },
        {
          ward: 'Kipawa',
          streets: [
            'Mogo',
            'Karakata',
            'Kipunguni',
            'Stakishari',
            'Uwanja Wa Ndege',
            'Mjimpya',
          ],
        },
        {
          ward: 'Ukonga',
          streets: [
            'Mwembe Madafu',
            'Mazizini',
            'Markaz',
            'Mongo La Ndege',
            'Sabasaba',
          ],
        },
        {
          ward: 'Kiwalani',
          streets: ['Kigilagila', 'Yombo', 'Kiwalani'],
        },
        {
          ward: 'Vingunguti',
          streets: [
            'Kombo',
            'Miembeni',
            'Mtakuja',
            'Mtambani',
            'Butiama',
            'Majengo',
          ],
        },
        {
          ward: 'Gongo La Mboto',
          streets: [
            'Guluka Kwalala',
            'Gongo La Mboto',
            'Ulongoni A',
            'Ulongoni B',
          ],
        },
        {
          ward: 'Kitunda',
          streets: ['Kipera', 'Kitunda', 'Relini', 'Kiyombo'],
        },
        {
          ward: 'Pugu',
          streets: [
            'Kinyamwezi',
            'Bombani',
            'Kigogo Fresh A',
            'Kigogo Fresh B',
            'Mustapha',
          ],
        },
        {
          ward: 'Majohe',
          streets: ['Mji Mpya', 'Kichangani', 'Kivule', 'Rada', 'Viwege'],
        },
        {
          ward: 'Msongola',
          streets: [
            'Kitonga',
            'Yangeyange',
            'Mbondole',
            'Mvuleni',
            'Kiboga',
            'Kidole',
            'Mkera',
            'Sangara',
            'Uwanja Wa Nyani',
          ],
        },
        {
          ward: 'Chanika',
          streets: [
            'Tungini',
            'Yongwe',
            'Lukomi',
            'Vikongoro',
            'Nguvu Mpya',
            'Virobo',
            'Kidugalo',
            'Ngwale',
            'Lukooni',
          ],
        },
        {
          ward: 'Kinyerezi',
          streets: [
            'Kinyerezi',
            'Kifuru',
            'Kwalimbaga',
            'Kanga',
            'Kichangani',
            'Kibaga',
          ],
        },
        {
          ward: 'Kivule',
          streets: ['Kivule', 'Bombambili', 'Karezange', 'Magore A'],
        },
        {
          ward: 'Mnyamani',
          streets: ['Maluzuku', 'Mji Mpya', 'Faru', 'Mnyamani'],
        },
        {
          ward: 'Liwiti',
          streets: ['Machimbo', 'Liwiti', 'Misewe', 'Amani'],
        },
        {
          ward: 'Bonyokwa',
          streets: ['Bonyokwa', 'Kisiwani', 'Msingwa'],
        },
        {
          ward: 'Kipunguni',
          streets: ['Kipunguni B', 'Kitinye', 'Machimbo', 'Amani'],
        },
        {
          ward: 'Kisukulu',
          streets: ['Luhanga', 'Kisukulu', 'Mianzini'],
        },
        {
          ward: 'Minazi Mirefu',
          streets: ['Mwale', 'Migombani', 'Minazi Mirefu'],
        },
        {
          ward: 'Buyuni',
          streets: [
            'Zavala',
            'Mgeule',
            'Nyeburu',
            'Kigezi',
            'Kigezi Chini',
            'Mgeule Juu',
            'Taliani',
          ],
        },
        {
          ward: 'Zingiziwa',
          streets: [
            'Nzasa',
            'Zogoali',
            'Zingiziwa',
            'Lubakaya',
            'Kimwani',
            'Ngobedi',
            'Somelo',
            'Gogo',
          ],
        },
        {
          ward: 'Mzinga',
          streets: ['Mwanagati', 'Magole', 'Mzinga'],
        },
        {
          ward: 'Pugu Station',
          streets: ['Bangulo', 'Pugu Station', 'Kichangani'],
        },
      ],
    },
    {
      district: 'Kinondoni',
      wards: [
        {
          ward: 'Magomeni',
          streets: ['Suna', 'Makuti A', 'Makuti B', 'Dossi', 'Idrisa'],
        },
        {
          ward: 'Mzimuni',
          streets: ['Idrisa', 'Makumbusho', 'Mtambani', 'Mwinyimkuu'],
        },
        {
          ward: 'Ndugumbi',
          streets: ['Mpakani', 'Mikoroshini', 'Makanya', 'Vigaeni'],
        },
        {
          ward: 'Tandale',
          streets: [
            'Mtogole',
            'Kwa Tumbo',
            'Pakacha',
            'Sokoni',
            'Mkunduge',
            'Muhaltani',
          ],
        },
        {
          ward: 'Makumbusho',
          streets: [
            'Makumbusho',
            'Minazini',
            'Mchangani',
            'Kisiwani',
            'Mbuyuni',
            'Singano',
          ],
        },
        {
          ward: 'Mwananyamala',
          streets: [
            'Kambangwa',
            'Msisiri B',
            'Msisiri A',
            'Bwawani',
            'Mwinjuma',
            'Kwa Kopa',
            'Msolomi',
          ],
        },
        {
          ward: 'Hananasif',
          streets: [
            'Hananasif',
            'Kisutu',
            'Mkunguni A',
            'Mkunguni B',
            'Kawawa',
          ],
        },
        {
          ward: 'Kinondoni',
          streets: [
            'Kumbukumbu',
            'Kinondoni Mjini',
            'Kinondoni Shamba',
            'Ada Estate',
          ],
        },
        {
          ward: 'Msasani',
          streets: [
            'Oysterbay',
            'Masaki',
            'Mikoroshoni',
            'Bonde La Mpunga',
            'Makangira',
          ],
        },
        {
          ward: 'Mikocheni',
          streets: [
            'Mikocheni A',
            'Mikocheni B',
            'Regent Estate',
            'Ally H. Mwinyi',
            'Tpdc',
            'Darajani',
          ],
        },
        {
          ward: 'Kijitonyama',
          streets: [
            'Kijitonyama',
            'Alimaua A',
            'Alimaua B',
            'Mpakani A',
            'Mpakani B',
            'Bwawani',
            'Mwenge',
            'Nzasa',
          ],
        },
        {
          ward: 'Kigogo',
          streets: ['Kigogo Kati', 'Kigogo Mkwajuni', 'Kigogo Mbuyuni'],
        },
        {
          ward: 'Kawe',
          streets: [
            'Mzimuni',
            'Ukwamani',
            'Mbezi  Beach  A',
            'Mbezi  Beach  B',
          ],
        },
        {
          ward: 'Kunduchi',
          streets: [
            'Pwani',
            'Kilongawima',
            'Mtongani',
            'Tegeta',
            'Ununio',
            'Kondo',
          ],
        },
        {
          ward: 'Bunju',
          streets: [
            'Boko',
            'Bunju A',
            'Kilungule',
            'Busihaya',
            'Dovya',
            'Mkoani',
          ],
        },
        {
          ward: 'Mbweni',
          streets: [
            'Maputo',
            'Mbweni',
            'Teta',
            'Malindi Estate',
            'Mpiji Mbweni',
          ],
        },
        {
          ward: 'Mbezi Juu',
          streets: [
            'Jogoo',
            'Ndumbwi',
            'Mbezi Mtoni',
            'Mbezi Kati',
            'Mbezi Juu',
          ],
        },
        {
          ward: 'Makongo',
          streets: ['Changanyikeni', 'Mbuyuni', 'Mlalakuwa', 'Makongo'],
        },
        {
          ward: 'Wazo',
          streets: [
            'Wazo',
            'Salasala',
            'Kilimahewa',
            'Madale',
            'Mivumoni',
            'Kisanga',
            'Kilimahewa Juu',
            'Nakasangwe',
          ],
        },
        {
          ward: 'Mabwepande',
          streets: ['Bunju B', 'Mabwe Pande', 'Mjimpya', 'Kihonzile', 'Mbopo'],
        },
      ],
    },
    {
      district: 'Temeke',
      wards: [
        {
          ward: 'Temeke',
          streets: ['Maganga', 'Matumbi', 'Njaro', 'Temeke'],
        },
        {
          ward: 'Sandali',
          streets: [
            'Mamboleo A',
            'Sandali',
            'Mamboleo B',
            'Mpogo',
            'Mwembeladu',
            'Tindwa',
            'Mkwida',
            'Veterinary',
            'Usalama',
            'Kimbunga',
            'Mwembemnofu',
            'Kisiwani',
          ],
        },
        {
          ward: 'Chang’ombe',
          streets: ['Bora', 'Toroli', "Chang'ombe A", "Chang'ombe B"],
        },
        {
          ward: 'Keko',
          streets: [
            'Keko B',
            'Keko Mwanga A',
            'Keko Mwanga B',
            'Keko Magurumbasi A',
            'Keko Magurumbasi B',
          ],
        },
        {
          ward: 'Miburani',
          streets: [
            'Miburani',
            'Uwanja Wa Taifa',
            'Wailes',
            'Keko Machungwa',
            'Mgulani (keko Juu)',
          ],
        },
        {
          ward: 'Azimio',
          streets: [
            'Azimio Kaskazini',
            'Azimio Kusini',
            'Kichangani',
            'Tambukareli',
            'Mji Mpya',
            'Mtongani',
            'Mtoni Unguja',
            'Mbuyuni',
          ],
        },
        {
          ward: 'Tandika',
          streets: [
            'Tamla',
            'Maguruwe',
            'Kilimahewa',
            'Tandika',
            'Nyambwera',
            'Mabatini',
          ],
        },
        {
          ward: 'Mtoni',
          streets: [
            'Mtoni',
            'Sabasaba',
            'Bustani',
            'Relini',
            'Chaurembo',
            'Bokorani',
          ],
        },
        {
          ward: 'Kurasini',
          streets: [
            'Shimo La Udongo',
            'Mivinjeni',
            'Minazini',
            'Kurasini',
            'Kiungani',
          ],
        },
        {
          ward: 'Mbagala Kuu',
          streets: [
            'Kizuiani',
            'Kibonde Maji B',
            'Kichemchem',
            'Jeshi La Wokovu',
            'Mbagala Kuu Mashariki',
            'Mbagala Kuu Magharibi',
            'Mbagala Kuu Kaskazini',
            'Makuka Kusini',
            'Makuka Kaskazini',
            'Mpakani',
          ],
        },
        {
          ward: 'Mbagala',
          streets: [
            'Mbagala',
            'Kizinga',
            'Mangaya',
            'Moringe',
            'Bughudadi',
            'Serenge',
          ],
        },
        {
          ward: 'Makangarawe',
          streets: ['Makangarawe', 'Yombo Dovya', 'Msakala', 'Uwazi', 'Mbonde'],
        },
        {
          ward: 'Yombo Vituka',
          streets: [
            'Yombo Vituka',
            'Sigara',
            'Machimbo',
            'Magogoni',
            'Mzambarauni',
          ],
        },
        {
          ward: 'Chamazi',
          streets: [
            'Magengeni',
            'Mwembebamia',
            'Kiponza',
            'Kisewe',
            'Rufu',
            'Msufini',
            'Vigoa',
            'Dovya',
            'Mkondogwa',
          ],
        },
        {
          ward: 'Charambe',
          streets: [
            'Kurasini Mji Mpya',
            'Nzasa B',
            'Rangi Tatu',
            'Machinjioni A',
          ],
        },
        {
          ward: 'Toangoma',
          streets: [
            'Toangoma',
            'Malela',
            'Vikunai',
            'Masuliza',
            'Masaki',
            'Mikwambe',
            'Changanyikeni',
            'Mwapemba',
            'Ponde',
            'Kongowe',
            'Goroka A',
            'Goroka B',
            'Mzinga A',
            'Mzinga B',
          ],
        },
        {
          ward: 'Buza',
          streets: ['Buza', 'Mji Mpya', 'Mashine Ya Maji', 'Kidagaa', 'Amani'],
        },
        {
          ward: 'Kilakala',
          streets: [
            'Barabara Ya Mwinyi',
            'Kilakala',
            'Kigunga',
            'Kiembesamaki',
            'Yombo Reli',
          ],
        },
        {
          ward: 'Kiburugwa',
          streets: [
            'Juhudi',
            'Kiburugwa Namba3',
            'Kwanyoka',
            'Kingugi',
            'Barabara Ya Mwinyi',
            'Kiburugwa',
          ],
        },
        {
          ward: 'Kijichi',
          streets: [
            'Mgeni Nani',
            'Misheni',
            'Mtoni Kijichi',
            'Butiama',
            'Mwanamtoti',
          ],
        },
        {
          ward: 'Mianzini',
          streets: ['Majimatitu A', 'Machinjioni', 'Mponda', 'Mianzini'],
        },
        {
          ward: 'Kibondemaji',
          streets: [
            'Majimatitu',
            'Kibondemaji A',
            'Mchikichini',
            'Kimbangulile',
          ],
        },
        {
          ward: 'Kilungule',
          streets: [
            'Kilungule',
            'Nzasa A',
            'Majimatitu B',
            'Kwa Mzungu',
            'Uzombokoni',
          ],
        },
      ],
    },
    {
      district: 'Ubungo',
      wards: [
        {
          ward: 'Mburahati',
          streets: ['Kisiwani', 'National Housing Corp', 'Barafu'],
        },
        {
          ward: 'Sinza',
          streets: ['Sinza A', 'Sinza B', 'Sinza C', 'Sinza D', 'Sinza E'],
        },
        {
          ward: 'Ubungo',
          streets: [
            'Chuo Kikuu',
            'Kisiwani',
            'Kibo',
            'Msewe',
            'National Housing Corp.',
          ],
        },
        {
          ward: 'Kimara',
          streets: [
            'Baruti',
            'Kimara Baruti',
            'Mavurunza',
            'Kilungule A',
            'Kilungule  B',
            'Golani',
          ],
        },
        {
          ward: 'Saranga',
          streets: [
            'Saranga',
            'Upendo',
            'KimaraB',
            'Matangini',
            'Stop Over',
            "King'ongo",
            'Michungwani',
            'Ukombozi',
            'Mji Mpya',
          ],
        },
        {
          ward: 'Makuburi',
          streets: [
            'Mwongozo',
            'Makoka',
            'Kibangu',
            'Makuburi Kibangu',
            'Kajima',
          ],
        },
        {
          ward: 'Makurumla',
          streets: [
            'Kwa Jongo',
            'Kimamba',
            'Kilimahewa',
            'Kagera',
            'Mianzini',
            'Sisi Kwa Sisi',
          ],
        },
        {
          ward: 'Manzese',
          streets: [
            'Midizini',
            'Kilimani',
            'Mnazi Mmoja',
            'Muungano',
            'Uzuri',
            'Mvuleni',
            'Mwembeni',
            'Chakula Bora',
            'Tupendane',
            'Mferejini',
          ],
        },
        {
          ward: 'Mabibo',
          streets: [
            'Mabibo',
            'Jitegemee',
            'Azimio',
            'Kanuni',
            'Matokeo',
            'Mabibo Farasi',
          ],
        },
        {
          ward: 'Kibamba',
          streets: ['Kibwegere', 'Kibamba', 'Hondogo', 'Gogoni', 'Kiluvya'],
        },
        {
          ward: 'Kwembe',
          streets: [
            'Kwembe',
            'Mpakani',
            "King'azi",
            'Luguruni',
            'Kisopwa',
            'Njeteni',
            "King'azi B",
            'Mjimpya',
            'Msakuzi',
            'Mlongazila',
          ],
        },
        {
          ward: 'Goba',
          streets: [
            'Goba',
            'Matosa',
            'Kulangwa',
            'Kinzudi',
            'Kunguru',
            'Kibululu',
            'Tegeta A',
            'Muungano',
          ],
        },
        {
          ward: 'Mbezi',
          streets: [
            'Msakuzi',
            'Msumi',
            'Mbezi Luis',
            'Mpiji Magohe',
            'Makabe',
            'Mshikamano',
            'Msakuzi Kusini',
            'Luis',
          ],
        },
        {
          ward: 'Msigani',
          streets: [
            'Temboni',
            'Malamba Mawili',
            'Kwa Yusuph',
            'Msigani',
            'Msingwa',
          ],
        },
      ],
    },
    {
      district: 'Kigamboni',
      wards: [
        {
          ward: 'Kimbiji',
          streets: [
            'Golani',
            'Kwa Chale',
            'Mikenge',
            'Ngobanya',
            'Kizito Huonjwa',
            'Kijaka',
          ],
        },
        {
          ward: 'Somangila',
          streets: [
            'Kizani',
            'Mbwamaji',
            'Mwera',
            'Dege',
            'Malimbika',
            'Visikini',
            'Bamba',
            'Mwanzo Mgumu',
            'Shirikisho',
            'Minondo',
            'Sara',
            'Mkwajuni',
            'Kichangani',
          ],
        },
        {
          ward: 'Tungi',
          streets: ['Tungi', 'Magogoni', 'Muungano'],
        },
        {
          ward: 'Kisarawe Ii',
          streets: [
            'Tumaini',
            'Kigogo',
            'Mwasonga',
            'Sharifu',
            'Vumilia Ukooni',
            'Ngoma Mapinduzi',
            'Mwaninga',
            'Mkamba',
            'Lingato',
            'Madege',
            'Kichangani',
          ],
        },
        {
          ward: 'Pembamnazi',
          streets: [
            'Potea',
            'Pu Centre',
            'Kwa Morisi',
            'Gulubwida',
            'Mahenge',
            'Tundwi Centre',
            'Songani Centre',
            'Pemba Centre',
            'Buyuni Centre',
            'Kibungo',
            'Kichangani',
            'Muhimbili',
            'Nyange',
            'Chambewa',
            'Mtimweupe',
          ],
        },
        {
          ward: 'Mjimwema',
          streets: ['Maweni', 'Ungindoni', 'Mjimwema', 'Kibugumo'],
        },
        {
          ward: 'Kigamboni',
          streets: ['Kigamboni', 'Ferry', 'Tuamoyo'],
        },
        {
          ward: 'Vijibweni',
          streets: [
            'Vijibweni',
            'Kibene',
            'Mkwajuni',
            'Kisiwani',
            'Upendo',
            'Majengo',
          ],
        },
        {
          ward: 'Kibada',
          streets: [
            'Nyakwale',
            'Kichangani',
            'Sokoni',
            'Kiziza',
            'Uvumba',
            'Kifurukwe',
          ],
        },
      ],
    },
  ],
};
