import { Region } from '../../../../ngx-mitaa.interfaces';

export const morogoro: Region = {
  region: 'Morogoro',
  districts: [
    {
      district: 'Morogoro\r\nCbd',
      wards: [
        {
          ward: 'Sultani Area',
          streets: [
            'Kikundi',
            'Ulugulu',
            'Umbunga',
            'Shule',
            'Mlali Road',
            'Ukwere',
            'Kati',
            'Kota',
            'Bushiri',
          ],
        },
        {
          ward: 'Mji Mkuu',
          streets: [
            'Short',
            'Boma Road',
            'Mlapakolo',
            'Amani',
            'Uhuru',
            'Karume A',
            'Karume B',
          ],
        },
        {
          ward: 'Sabasaba',
          streets: [
            'Betelo',
            'Makongoro',
            'Ngoto  A',
            'Polisi Kota',
            'Kingo',
            'Mlali',
            'Kikundi',
            'Mindu',
            'Ngoto B',
            'Kenyatta',
            'Konga',
            'John Mahenge',
          ],
        },
        {
          ward: 'Mafiga',
          streets: [
            'Kidondolo A',
            'Kidondolo B',
            'Madox',
            'Misufini',
            'Msikiti',
            'Kituo Cha Polisi',
            'Mafiga A',
            'Mafiga B',
            'Ccm',
            'Kambaya',
            'Majumba Saba',
            'Ngazengwa',
            'Zahanati',
            'Lusegwa',
            'Manzese',
          ],
        },
        {
          ward: 'Uwanja Wa Taifa',
          streets: [
            'Ukutu',
            'Maelewano A',
            'Maelewano B',
            'Kanisani',
            'Unguu B',
            'Kiswanya A',
            'Kiswanya  B',
            'Sabu',
            'Kidugalo',
            'Mindu',
            'Unguu A',
          ],
        },
        {
          ward: 'Kingo',
          streets: ['Reli', 'Mwere', 'Kingo', 'Salum Abdallah', 'Mango'],
        },
        {
          ward: 'Mji Mpya',
          streets: [
            'Makaburi A',
            'Makaburi B',
            'Makaburi C',
            'Fumilwa A',
            'Fumilwa B',
            'Fumilwa C',
            'Ngoma A',
            'Ngoma B',
            'Ngoma C',
            'Simu A',
            'Simu B',
            'Simu C',
          ],
        },
        {
          ward: 'Kiwanja Cha\r\nNdege',
          streets: [
            'Tumbaku',
            'Lukwagule',
            'Azimio',
            'Mtagwa',
            'Kiwalani',
            'Lusogo',
            'Ujenzi',
            'Kimunyu',
            'Bondwa',
            'Ngazengwa',
            'Lungo',
            'Lusanga',
            'Mkota',
          ],
        },
        {
          ward: 'Boma',
          streets: [
            'Kibwe',
            'Wamo',
            'Kihimbwa',
            'Rock Garden',
            'Nguzo',
            'Mzigila',
            'Jumbe Mtoto',
            'Old Dar Road',
            'Kingalu',
            "Kin'gola",
            'Forest Hill',
            'Forest Nhc',
            'Madizini',
            'Visole',
            'Msigala',
          ],
        },
        {
          ward: 'Kilakala',
          streets: [
            'Bigwa Kisiwani',
            'Bigwa Sokoni',
            'Ualimu',
            'Migombani',
            'Kolla',
            'Mahedu',
            'Kigurunyembe',
            'Kigurunyembe\r\nMizambarauni',
            "Ng'atigwa",
            'Bwinila',
            'Kilakala',
            'Mbogo',
            "Bong'ola",
            'Nughutu',
            'Chalumbi',
          ],
        },
        {
          ward: 'Bigwa',
          streets: [
            'Bigwa Barabarani',
            'Stendi',
            'Lukuyu',
            'Kindimbwa',
            'Misongeni A',
            'Zahanati',
            'Misongeni B',
            'Transfoma',
            'Bohomela',
            'Vituli',
            'Mgolole',
            'Korogoso',
            'Mungi',
          ],
        },
        {
          ward: 'Kichangani',
          streets: [
            'Kola B',
            'Kola A',
            'Area Six',
            'Area Six B',
            'Area Five',
            'Mchuma',
            'Railways Estate',
            'Mwande',
            'Mkwajuni',
            'Karakana',
            'Kichangani',
            'Fungafunga',
          ],
        },
        {
          ward: 'Mwembesongo',
          streets: [
            'Mwigole',
            'Mkwajuni',
            'Sume',
            'Mzambarauni',
            'Juma Hamsini',
            'Saadan C',
            'Magodoro',
            'Mwanzo Mgumu',
            'Mfungua Kinywa',
            'Genda',
            'Gohalema',
            'Mtawala',
            'Riverside',
            'Mwembesongo',
            'Makaburi',
            'Ndege Wengi',
          ],
        },
        {
          ward: 'Kihonda',
          streets: [
            'Kilimanjaro',
            'Yespa',
            'Kilombero',
            'Kihonda B',
            'Kihonda Kaskazini',
            'Msimamo',
            'Azimio',
            'Magereza',
            'Nguvu Kazi',
            'Kiegea A',
          ],
        },
        {
          ward: 'Mazimbu',
          streets: [
            'Mazimbu Darajani',
            'Boma',
            'Boma B',
            'Modeco A',
            'Modeco B',
            'Nguzo',
            'Reli',
          ],
        },
        {
          ward: 'Mbuyuni',
          streets: [
            'Mtoni B',
            'Magurumbasi',
            'Mgonahazeru',
            'Bambalawe',
            'Sabasaba',
            'Mtoni A',
          ],
        },
        {
          ward: 'Mlimani',
          streets: [
            'Mbete',
            'Kireka',
            'Choma',
            'Kisosa',
            'Nyandila',
            'Liti',
            'Kikundi',
            'Ruvuma',
            "Mng'ongo",
            'Tulo',
            'Chalagule',
          ],
        },
        {
          ward: 'Mzinga',
          streets: ['Kidangawa', 'Misasa', 'Konga A', 'Mtoni', 'Konga B'],
        },
        {
          ward: 'Kingolwira',
          streets: [
            'Zahanati',
            'Seminari',
            'Mahakama',
            'Tambuka Reli',
            'Tangi La Maji',
            'Shule',
            'Bomba La Zambia',
            'Mwembe Msafa',
          ],
        },
        {
          ward: 'Lukobe',
          streets: [
            'Tuelewane',
            'Lukobe Juu',
            'Lukobe Kambi 5',
            'Mgudeni',
            'Maendeleo',
            'Manyuki',
            'Tushikamane',
            'Majengo Mapya',
          ],
        },
        {
          ward: 'Mafisa',
          streets: [
            'Sina',
            'Mambi',
            'Kayenzi',
            'Kihonda Mbuyuni',
            'Kilima Hewa',
            'White House',
            'Nyerere',
            'Mafisa',
          ],
        },
        {
          ward: 'Tungi',
          streets: [
            'Nanenane',
            'Nanenane B',
            'Mji Mwema',
            'Mji Mwema B',
            'Tubuyu',
            'Tubuyu B',
            'Mfuruni',
            'Mkwajuni',
            'Mfaranyaki',
            'Tungi Kambini A',
            'Mafisa',
            'Tungi Kambini B',
          ],
        },
        {
          ward: 'Kauzeni',
          streets: [
            'Kauzeni',
            'Viswayu',
            'Tindigo',
            'Minazini',
            'Gezaulole',
            'Nyambutwa',
          ],
        },
        {
          ward: 'Luhungo',
          streets: [
            'Mambani',
            'Mundu',
            'Kilala',
            'Kivaza',
            'Mlulu',
            'Mfine',
            'Mkoya',
          ],
        },
        {
          ward: 'Magadu',
          streets: [
            'Magadu',
            'Tiba Sua/road',
            'Kilimo Sua',
            'Folk Land',
            'Mgambazi',
            'Kididimo Sua',
            'Kididimo',
            'Baraka',
          ],
        },
        {
          ward: 'Mkundi',
          streets: [
            'Maili 18',
            'Mawasiliano',
            'Mgulu Ya Ndege',
            'Kilongo',
            'Kilongo B',
            'Mlimani',
            'Bwawani',
            'Cct Forest',
            'Kiegea B',
            'Kipera',
            'Ngerengere',
          ],
        },
        {
          ward: 'Chamwino',
          streets: [
            'Msikitini',
            'Misufini',
            'Mwande',
            'Shule',
            'Tupendane',
            'Mgulasi',
            'Napome',
            'Chamwino',
            'Usalama',
            'Visegese',
            'Mwembeni',
            'Mahita',
            'Kiwalani',
            'Malipula',
            'Mafiga Sua',
          ],
        },
        {
          ward: 'Kihonda\r\nMaghorofani',
          streets: [
            'Kihonda Maghorofani',
            'Kihonda Maghorofani B',
            'Msamvu B',
            'Godes',
            'Air Port',
            'Bima',
            'Ngerengere',
            'Mbuyuni',
            'Kitata',
          ],
        },
        {
          ward: 'Mindu',
          streets: [
            'Kasanga',
            'Mgaza',
            'Mindu',
            'Mikoroshini',
            'Madaganya',
            'Mkwajuni',
            'Lugala',
            'Mazimbu Campus',
          ],
        },
      ],
    },
    {
      district: 'Morogoro',
      wards: [
        {
          ward: 'Tegetero',
          streets: ['Tegetero', 'Bagilo', 'Hewe', 'Mifulu'],
        },
        {
          ward: 'Kinole',
          streets: [
            'Tandai',
            'Amini',
            'Kalundwa',
            'Rudewa',
            'Mangala',
            "Lung'ala",
          ],
        },
        {
          ward: 'Mkuyuni',
          streets: ['Mkuyuni', 'Mfumbwe', 'Changa', 'Madamu', 'Kibwaya'],
        },
        {
          ward: 'Kiroka',
          streets: ['Kiroka', 'Diovuva', 'Kiziwa', 'Bamba'],
        },
        {
          ward: 'Mkalambani',
          streets: ['Mkalambani', 'Mkono Wa Mara', 'Kizinga', 'Pangawe'],
        },
        {
          ward: 'Mikese',
          streets: [
            'Mikese Mjini',
            'Fulwe',
            'Mtego Wa Simba',
            'Newland',
            'Mhunga Mkola',
            "Lubungo 'a'",
          ],
        },
        {
          ward: 'Gwata',
          streets: ['Gwataujembe', 'Kinonko', 'Maseyu'],
        },
        {
          ward: 'Ngerengere',
          streets: ['Ngerengere', 'Mgude', 'Kiwege', 'Sinyaulime'],
        },
        {
          ward: 'Matuli',
          streets: ['Matuli', 'Kwaba', 'Lulongwe', 'Diguzi'],
        },
        {
          ward: 'Kidugalo',
          streets: [
            'Kidugalo',
            'Pulambili',
            'Visaraka',
            'Kisemo',
            'Magera',
            "Seregete 'a'",
            "Seregete 'b'",
            'Lubumu',
          ],
        },
        {
          ward: 'Mkulazi',
          streets: ['Mkulazi', 'Kidunda', 'Chanyumbu', 'Usungura'],
        },
        {
          ward: 'Tununguo',
          streets: ['Tununguo', 'Kisanga Stendi', 'Dete', 'Mlilingwa'],
        },
        {
          ward: 'Lundi',
          streets: [
            'Lundi',
            "Ngong'olo",
            'Misaga',
            'Tambuu',
            'Muungano',
            'Vihengele',
          ],
        },
        {
          ward: 'Tawa',
          streets: [
            'Tawa',
            'Kisarawe',
            'Kifindike',
            'Milawilila',
            'Uponda',
            'Kilemela',
            'Kitungwa',
            'Logo',
          ],
        },
        {
          ward: 'Kisemu',
          streets: ['Mtamba', 'Gozo', 'Nige', 'Kibangile'],
        },
        {
          ward: 'Konde',
          streets: ['Konde', 'Mlono', 'Kiswila'],
        },
        {
          ward: 'Mtombozi',
          streets: [
            'Mtombozi',
            'Kibwege',
            'Lugeni',
            "Ng'weme",
            'Lusange',
            'Tandali',
            'Baga',
          ],
        },
        {
          ward: 'Kasanga',
          streets: ['Kasanga', 'Ukwama', 'Longwe', 'Kitonga', 'Kizagila'],
        },
        {
          ward: 'Bungu',
          streets: ['Bungu', 'Balani', 'Mihange', 'Koloni'],
        },
        {
          ward: 'Mvuha',
          streets: ['Mvuha', 'Dala', 'Msonge', 'Kongwa', 'Lukulunge', 'Tulo'],
        },
        {
          ward: 'Selembala',
          streets: [
            'Magogoni',
            'Kiganila',
            'Bwila Chini',
            'Bwila Juu',
            'Kiburumo',
          ],
        },
        {
          ward: 'Kisaki',
          streets: ['Gomero', 'Nyarutanga', 'Kisaki Kituoni', 'Kichangani'],
        },
        {
          ward: 'Bwakira Chini',
          streets: ['Bwakira Chini', 'Mbwade', 'Bonye', 'Dakawa'],
        },
        {
          ward: 'Kolero',
          streets: [
            'Kolero',
            'Temekero',
            'Lukange',
            'Mlagano',
            'Malani',
            'Lubasazi',
          ],
        },
        {
          ward: 'Bwakira Juu',
          streets: ['Bwakira Juu', 'Kumba', 'Mgata'],
        },
        {
          ward: 'Mngazi',
          streets: ['Mngazi', 'Vigolegole', 'Sesenga', 'Milengwelengwe'],
        },
        {
          ward: 'Singisa',
          streets: [
            'Singisa',
            "Nyamigadu 'a'",
            'Ntala',
            "Nyamigadu 'b'",
            'Lumba Chini',
            'Kitengu',
            'Lumba Juu',
          ],
        },
        {
          ward: 'Kibungo',
          streets: ['Lukenge', 'Dimilo', 'Kibungo', 'Lanzi', 'Nyingwa'],
        },
        {
          ward: 'Kibogwa',
          streets: [
            'Kibogwa',
            'Nyachiro',
            'Kaloni',
            'Kilunga',
            'Mambani',
            'Kifulu',
          ],
        },
        {
          ward: 'Kibuko',
          streets: ['Kibuko', 'Luholole', 'Kivuma', 'Mwarazi'],
        },
        {
          ward: 'Tomondo',
          streets: ['Kikundi', 'Lukonde', 'Kungwe', 'Vuleni'],
        },
      ],
    },
    {
      district: 'Mvomero',
      wards: [
        {
          ward: 'Mvomero',
          streets: ['Mvomero', 'Makuyu', 'Mgudeni', 'Dibamba', 'Matale'],
        },
        {
          ward: 'Dakawa',
          streets: [
            'Wami Luhindo',
            'Wami Sokoine',
            'Wami Dakawa',
            'Kwa Mhunzi',
            'Milama',
          ],
        },
        {
          ward: 'Hembeti',
          streets: ['Hembeti', 'Dihombo', 'Msufini', 'Kisimangulu'],
        },
        {
          ward: 'Mtibwa',
          streets: [
            'Madizini',
            'Kunke',
            'Kidudwe',
            'Mlumbilo',
            'Lukenge',
            'Lungo',
          ],
        },
        {
          ward: 'Sungaji',
          streets: [
            'Kilimanjaro',
            'Kisala',
            'Komtonga',
            'Mlaguzi',
            'Mbogo',
            'Kigugu',
          ],
        },
        {
          ward: 'Mhonda',
          streets: ['Kichangani', 'Mhonda', 'Kwelikweiji'],
        },
        {
          ward: 'Maskati',
          streets: ['Maskati', 'Dibago', 'Kipangilo', 'Magunga'],
        },
        {
          ward: 'Kibati',
          streets: ['Dibuluma', 'Kibogoji', 'Pandambili', 'Hoza', 'Salawe'],
        },
        {
          ward: 'Diongoya',
          streets: ['Manyinga', 'Digoma', 'Lusanga', 'Kwadoli', 'Digalama'],
        },
        {
          ward: 'Kanga',
          streets: ['Difinga', 'Kanga', 'Dihinda'],
        },
        {
          ward: 'Mzumbe',
          streets: [
            'Tangeni',
            'Mnyanza',
            'Changarawe',
            'Sangasanga',
            'Vikenge',
          ],
        },
        {
          ward: 'Melela',
          streets: ['Melela', 'Kibaoni', 'Magali'],
        },
        {
          ward: 'Mlali',
          streets: [
            'Mlali',
            'Pekomisegese',
            'Vitonga',
            'Mkuyuni',
            'Kipera',
            'Lugono',
            'Kinyenze',
            'Mongwe',
          ],
        },
        {
          ward: 'Bunduki',
          streets: ['Kibigiri', 'Bunduki', 'Tandali', 'Vinile', 'Maguruwe'],
        },
        {
          ward: 'Langali',
          streets: ['Pinde', 'Langali', 'Bumu'],
        },
        {
          ward: 'Tchenzema',
          streets: ['Tchenzema', 'Mwarazi', 'Kibuko'],
        },
        {
          ward: 'Kikeo',
          streets: ['Kikeo', 'Mhale', "Ng'owo", 'Chohelo', 'Lukunguni'],
        },
        {
          ward: 'Doma',
          streets: [
            'Doma',
            'Maharaka',
            'Sewekipera',
            'Misengele',
            'Dasi',
            'Kihondo',
          ],
        },
        {
          ward: 'Pemba',
          streets: ['Pemba', 'Gonja', 'Masimba', 'Msolokelo'],
        },
        {
          ward: 'Kinda',
          streets: ['Ndole', 'Kinda', 'Semwali', 'Makate'],
        },
        {
          ward: 'Mgeta',
          streets: ['Lusungi', 'Kibaoni', 'Lukuyu'],
        },
        {
          ward: 'Luale',
          streets: ['Luale', 'Kododo', 'Masalawe', 'Londo'],
        },
        {
          ward: 'Nyandira',
          streets: ['Nyandira', "Ng'ungulu", 'Ndugutu', 'Kibagala'],
        },
        {
          ward: 'Mangae',
          streets: ['Mela', 'Mlandizi', 'Mangae'],
        },
        {
          ward: 'Homboza',
          streets: ['Homboza', 'Chohero', 'Manza', 'Yowe'],
        },
        {
          ward: 'Lubungo',
          streets: ['Lubungo B', 'Mingo', 'Kimambila', 'Vianzi', 'Mafuru'],
        },
        {
          ward: 'Msongozi',
          streets: ['Msongozi', 'Mitupile', 'Mkata'],
        },
        {
          ward: 'Mkindo',
          streets: ['Mkindo', 'Bungoma', 'Kambala', 'Mndela'],
        },
        {
          ward: 'Kichangani',
          streets: ['Luwamba', 'Mafuta', 'Ubiri'],
        },
        {
          ward: 'Mziha',
          streets: ['Mziha', 'Kibatula', 'Njeula', 'Kaole', 'Bwage'],
        },
      ],
    },
    {
      district: 'Kilosa',
      wards: [
        {
          ward: 'Kasiki',
          streets: ['Bwage'],
        },
        {
          ward: 'Mbumi',
          streets: ['Bwage'],
        },
        {
          ward: 'Mkwatani',
          streets: ['Bwage'],
        },
        {
          ward: 'Magubike',
          streets: ['Chaumbele"a"', 'Mwandi'],
        },
        {
          ward: 'Parakuyo',
          streets: ['Twatwatwa', 'Parakuyo', 'Ngaite', 'Mkata Station'],
        },
        {
          ward: 'Berega',
          streets: ['Berega'],
        },
        {
          ward: 'Mamboya',
          streets: ['Nyangala "a"', 'Uponela', 'Mwisini'],
        },
        {
          ward: 'Mvumi',
          streets: ['Makwambe', 'Mhowe', 'Mvumi', 'Gongwe'],
        },
        {
          ward: 'Maguha',
          streets: ['Ibindo', 'Maguha', 'Nyangala Bondeni', 'Inyunywe'],
        },
        {
          ward: 'Mabula',
          streets: ['Mabula', 'Mbili', 'Nhembo', 'Magera'],
        },
        {
          ward: 'Mtumbatu',
          streets: ['Mtumbatu'],
        },
        {
          ward: 'Malolo',
          streets: ['Malolo"a"', 'Malolo "b"', 'Mgogozi', 'Chabi'],
        },
        {
          ward: 'Kisanga',
          streets: ['Kisanga', 'Wedo', 'Madizini', 'Msolwa', 'Mululu'],
        },
        {
          ward: 'Ruhembe',
          streets: ['Ruhembe', 'Kihelezo', 'Kidogobasi', 'Kitete Msindazi'],
        },
        {
          ward: 'Ruaha',
          streets: ['Ruaha'],
        },
      ],
    },
    {
      district: 'Kilombero',
      wards: [
        {
          ward: "Mang'ula",
          streets: ['Mang\'ula "a"', 'Msalise'],
        },
        {
          ward: 'Mkula',
          streets: ['Magombera', 'Katurukila', 'Sole', 'Msufini', 'Mkula'],
        },
        {
          ward: 'Kidatu',
          streets: [
            'Kidatu "a"',
            'Kidatu "b"',
            'Kidatu Kati',
            'Mkamba',
            'Chikago',
          ],
        },
        {
          ward: 'Lumemo',
          streets: ['Lumemo', 'Mahutanga', 'Ihanga'],
        },
        {
          ward: 'Idete',
          streets: ['Idete', 'Idete "b"', 'Miwangani'],
        },
        {
          ward: 'Mang\'ula "b"',
          streets: ['Kanyenja', 'Mang\'ula "b"', 'Mshikamano'],
        },
        {
          ward: 'Signal',
          streets: ['Signal', 'Sululu', 'Sagamanga'],
        },
        {
          ward: 'Katindiuka',
          streets: ['Katindiuka "b"', 'Katindiuka "c"'],
        },
        {
          ward: 'Lipangalala',
          streets: [
            'Kiyongwile',
            'Lipangalala',
            'Mkuya',
            'Mahakamani',
            'Kiyongwile "b"',
            'Lihami',
          ],
        },
        {
          ward: 'Mlabani',
          streets: ['Mlabani "a"', 'Mlabani "b"', 'Muungano', 'Mchangani'],
        },
        {
          ward: 'Viwanjasitini',
          streets: [
            'Mhola',
            'Viwanjasitini',
            'Viwandani',
            'Magengeni',
            'Jongo',
            'Matonga',
            'Viwanjasitini "b"',
            'Uwanja Wa Taifa "a"',
            'Uwanja Wa Taifa "b"',
            'Minarani',
          ],
        },
        {
          ward: "Ching'anda",
          streets: ["Ching'anda", 'Lufulu', 'Udagaji'],
        },
        {
          ward: 'Igima',
          streets: ['Mpofu', 'Igima', 'Namalumbo', 'Ngajenwa'],
        },
      ],
    },
    {
      district: 'Ulanga',
      wards: [
        {
          ward: 'Mahenge Mjini',
          streets: ['Mahenge', 'Safari Road'],
        },
        {
          ward: 'Vigoi',
          streets: ['Vigoi', 'Mbagula', 'Namgezi', 'Makanga'],
        },
        {
          ward: 'Isongo',
          streets: ['Isongo', 'Mbangayao'],
        },
        {
          ward: 'Msogezi',
          streets: ['Msogezi'],
        },
      ],
    },
  ],
};
