import { Region } from '../../../../ngx-mitaa.interfaces';

export const arusha: Region = {
  region: 'Arusha',
  districts: [
    {
      district: 'Arusha Cbd',
      wards: [
        {
          ward: 'Sekei',
          streets: [
            'Sanawari',
            'Naurei',
            'Mtaa Wa Aicc',
            'Mtaa Wa Mahakamani',
            'Naura',
            'Goliondoi',
          ],
        },
        {
          ward: 'Kati',
          streets: ['Bondeni', 'Pangani'],
        },
        {
          ward: 'Kaloleni',
          streets: ['Kaloleni Magharibi', 'Mita 200', 'Kaloleni Mashariki'],
        },
        {
          ward: 'Levolosi',
          streets: ['Mtaa Wa Levolosi', 'Majengo'],
        },
        {
          ward: 'Ngarenaro',
          streets: ['Kambi Ya Fisi', 'Darajani', 'Nhc', 'Tca', 'Mita 200'],
        },
        {
          ward: 'Elerai',
          streets: [
            'Kware',
            'Burka',
            'Azimio',
            'Shamsi',
            'Samanga',
            'Sacon',
            'Remtula',
            'Mama Musa',
            'Ngurumo',
            'Urundini',
            'Shuma',
            'Majengo “a”',
            'Majengo “b”',
          ],
        },
        {
          ward: 'Unga Limited',
          streets: [
            'Esso',
            'Viwandani',
            'Makaburi Ya Baniani',
            'Tindiga',
            'Darajani',
            'Osterbay',
          ],
        },
        {
          ward: 'Daraja Ii',
          streets: [
            'Jamhuri',
            'Alinyanya',
            'Sanare',
            'Ndarvoi',
            'Darajani',
            'Kati',
          ],
        },
        {
          ward: 'Themi',
          streets: [
            'Themi Mashariki',
            'Old Police',
            'Corridor Area',
            'Aicc Flats',
            'Kambarage',
          ],
        },
        {
          ward: 'Kimandolu',
          streets: [
            'Kitiangare',
            'Tindigani',
            'Kijenge Kaskazini',
            'Kijenge Kusini',
          ],
        },
        {
          ward: 'Olorieni',
          streets: ['Suye', 'Meirioti', 'Mwanama', 'Mbeshere', 'Moivoi', 'Rc'],
        },
        {
          ward: 'Baraa',
          streets: [
            'Kwa Mrefu',
            'Sorenyi',
            'Kiroshi',
            'Ofisini',
            'Kambi Ya Chupa',
            'Mferejini',
            'Siara',
            'Elkirouwa',
          ],
        },
        {
          ward: 'Lemara',
          streets: [
            'Ilkirouwa',
            'Olepholos',
            'Korongoni',
            'Kikwakwaru ‘a’',
            'Kikwakwaru‘b’',
            'Lemara Kati',
            'Sunflag',
          ],
        },
        {
          ward: 'Engutoto',
          streets: [
            'Block C1',
            'Block C2',
            'Block D',
            'Block F',
            'Block H',
            'Block J',
          ],
        },
        {
          ward: 'Sokon 1',
          streets: ['Lolovono'],
        },
        {
          ward: 'Sokon 2',
          streets: ['Longdong'],
        },
        {
          ward: 'Sokon 3',
          streets: ['Murriet'],
        },
        {
          ward: 'Sokon 4',
          streets: ['Kanisani'],
        },
        {
          ward: 'Sokon 5',
          streets: ['Sainevuno'],
        },
        {
          ward: 'Sokon 6',
          streets: ['Madukani'],
        },
        {
          ward: 'Sombetini',
          streets: ['Simanjiro', 'Banda Mbili', 'Kirika ‘a’', 'Olamurraki'],
        },
        {
          ward: 'Terrat',
          streets: [
            'Laitayok',
            "Imitong'wa",
            'Maskiria',
            'Bondeni Kati',
            'Olepolosi',
            'Erangau',
            'Olkungu',
            'Engavunet',
          ],
        },
        {
          ward: 'Moshono',
          streets: [
            'Nanja',
            'Moshono Kati',
            'Engosowash',
            'T.packers',
            'Olkereyan Kati',
            'Laizer',
            'Losirwaylaizer',
            'Mtoni',
            'Kalimaji',
          ],
        },
        {
          ward: 'Olasiti',
          streets: [
            'Kimindorosi',
            'Olasiti Centre',
            'Oloresho',
            'Olkereyan',
            'Burka',
            'Olteves',
          ],
        },
        {
          ward: 'Moivaro',
          streets: [
            'Edanyoemasi',
            'Moivaro Kati',
            'Shangarao',
            'Ngurumaus',
            'Sekei',
            'Moshono Kaskazini',
          ],
        },
        {
          ward: 'Sinoni',
          streets: [
            'Makao Mapya',
            'Olevolos',
            'Olomokeya',
            'Oljanvutian',
            'Mlimani',
            'Migungani',
            'Engosengiu',
          ],
        },
        {
          ward: 'Muriet',
          streets: [
            'Bondeni',
            'Kati',
            'Mashariki',
            'Murieti',
            'Mlimani',
            'Msasani',
            'Ffu',
            'Eluanyi',
            'Nadosoito Kusini',
            'Ngorienito',
            'Oldonyokumur',
            'Embararwai',
            'Kati',
          ],
        },
        {
          ward: 'Osunyai Jr',
          streets: ['Osunyai', 'Ngusero', "Kirika 'b'", 'Jr'],
        },
        {
          ward: 'Sakina',
          streets: [
            'Olmatejoo “a”',
            'Navarana',
            'Giriki',
            'Olmatejo “b”',
            'Mairiva',
            'Sakina',
            'Melamari',
          ],
        },
        {
          ward: 'Olmoti',
          streets: [
            'Olmoti',
            'Ngaramtoni Ya Chini',
            'Mlimani',
            'Mirongoine',
            'Nafco',
          ],
        },
      ],
    },
    {
      district: 'Arusha',
      wards: [
        {
          ward: 'Olturumet',
          streets: ['Nafco', 'Nafco', 'Nafco'],
        },
        {
          ward: 'Mwandet',
          streets: [
            'Imbibia',
            'Imbibia',
            'Imbibia',
            'Losikito',
            'Losikito',
            'Losikito',
            'Losikito',
            'Engalaoni',
            'Engalaoni',
            'Engalaoni',
            'Engurtoto',
            'Engurtoto',
            'Engurtoto',
            'Engurtoto',
          ],
        },
        {
          ward: 'Olkokola',
          streets: [
            'Olkejulenderit',
            'Olkejulenderit',
            'Olkejulenderit',
            'Ilkurot',
            'Ilkurot',
            'Lengijave',
            'Lengijave',
            'Lengijave',
            'Lengijave',
          ],
        },
        {
          ward: 'Oldonyosambu',
          streets: [
            'Oldonyosambu',
            'Oldonyosambu',
            'Oldonyosambu',
            "Lemong'o",
            "Lemong'o",
            "Lemong'o",
            'Lemanda',
            'Lemanda',
            'Lemanda',
          ],
        },
        {
          ward: 'Musa',
          streets: [
            'Oloitushula',
            'Oloitushula',
            'Oloitushula',
            "Nengung'u",
            "Nengung'u",
            'Olchorovus',
            'Olchorovus',
            'Olchorovus',
            'Likamba',
            'Likamba',
            'Likamba',
            'Likamba',
            'Likamba',
          ],
        },
        {
          ward: 'Kisongo',
          streets: [
            'Engorora',
            'Engorora',
            'Engorora',
            'Ilkerin',
            'Ilkerin',
            'Ilkerin',
            'Lesiraa',
            'Lesiraa',
            'Lesiraa',
            'Lesiraa',
            'Lovilukuny',
            'Lovilukuny',
          ],
        },
        {
          ward: 'Bangata',
          streets: [
            'Bangata',
            'Bangata',
            'Bangata',
            'Midawe',
            'Midawe',
            'Sasi',
            'Sasi',
            'Sasi',
          ],
        },
        {
          ward: 'Sokon Ii',
          streets: [
            'Sokon Ii',
            'Sokon Ii',
            'Sokon Ii',
            'Sokon Ii',
            'Sokon Ii',
            'Oldadai',
            'Oldadai',
            'Oldadai',
            'Oldadai',
            'Ngires',
            'Ngires',
            'Ngires',
            'Ngires',
            'Ngires',
            'Ngires',
          ],
        },
        {
          ward: 'Kiranyi',
          streets: ['Ngires', 'Ngires', 'Ngires', 'Ngires'],
        },
        {
          ward: 'Olorien',
          streets: ['Ngires', 'Ngires', 'Ngires'],
        },
        {
          ward: "Ilkiding'a",
          streets: [
            "Ilkiding'a",
            "Ilkiding'a",
            "Ilkiding'a",
            "Ilkiding'a",
            'Oloigeruno',
            'Oloigeruno',
            'Oloigeruno',
            'Oloigeruno',
            'Ilkisongo',
            'Ilkisongo',
            'Ilkisongo',
          ],
        },
        {
          ward: 'Sambasha',
          streets: [
            'Sambasha',
            'Sambasha',
            'Sambasha',
            'Shimboro',
            'Shimboro',
            'Shimboro',
            'Shimboro',
            'Timbolo',
            'Timbolo',
            'Timbolo',
            'Timbolo',
          ],
        },
        {
          ward: 'Kimnyaki',
          streets: [
            'Olmringaringa',
            'Olmringaringa',
            'Olmringaringa',
            'Olmringaringa',
            'Olovolos',
            'Olovolos',
            'Olovolos',
            'Olovolos',
            'Kimnyaki',
            'Kimnyaki',
            'Kimnyaki',
            'Kimnyaki',
          ],
        },
        {
          ward: 'Olmotonyi',
          streets: ['Kimnyaki', 'Kimnyaki', 'Kimnyaki'],
        },
        {
          ward: 'Oljoro',
          streets: [
            'Mirongoine',
            'Mirongoine',
            'Mirongoine',
            'Oljoro',
            'Oljoro',
            'Oljoro',
            'Mbuyuni',
            'Mbuyuni',
            'Mbuyuni',
            'Mbuyuni',
          ],
        },
        {
          ward: 'Olturoto',
          streets: [
            'Kivulul',
            'Kivulul',
            'Kivulul',
            'Oldonyosapuk',
            'Oldonyosapuk',
            'Oldonyosapuk',
            'Oldonyosapuk',
            'Oldonyosapuk',
            'Ilkirevi',
            'Ilkirevi',
            'Ilkirevi',
            'Osunyai',
            'Osunyai',
            'Osunyai',
          ],
        },
        {
          ward: 'Moivo',
          streets: ['Osunyai', 'Osunyai', 'Osunyai', 'Osunyai', 'Osunyai'],
        },
        {
          ward: 'Mlangarini',
          streets: [
            'Mlangarini',
            'Mlangarini',
            'Mlangarini',
            'Kiserian',
            'Kiserian',
            'Kiserian',
            'Kiserian',
            'Kiserian',
            'Kiserian',
            'Kiserian',
            'Kiserian',
            'Kiserian',
            'Manyire',
            'Manyire',
            'Manyire',
            'Manyire',
          ],
        },
        {
          ward: 'Nduruma',
          streets: [
            'Nduruma',
            'Nduruma',
            'Nduruma',
            'Nduruma',
            'Samaria',
            'Samaria',
            'Samaria',
            'Samaria',
            'Marurani',
            'Marurani',
            'Marurani',
            'Marurani',
            'Marurani',
            'Maji Moto',
            'Maji Moto',
            'Maji Moto',
          ],
        },
        {
          ward: 'Bwawani',
          streets: [
            'Bwawani',
            'Bwawani',
            'Bwawani',
            'Bwawani',
            'Bwawani',
            'Bwawani',
            'Themi Ya Simba',
            'Themi Ya Simba',
            'Themi Ya Simba',
            'Mungushi',
            'Mungushi',
            'Mungushi',
            'Mungushi',
            'Kigongoni',
            'Kigongoni',
          ],
        },
        {
          ward: 'Mateves',
          streets: [
            'Ngorbob',
            'Ngorbob',
            'Ngorbob',
            'Ngorbob',
            'Ngorbob',
            'Lemugur',
            'Lemugur',
            'Lemugur',
          ],
        },
        {
          ward: 'Lemanyata',
          streets: [
            'Lemanyata',
            'Lemanyata',
            'Lemanyata',
            'Olkokola',
            'Olkokola',
            'Olkokola',
            'Olkokola',
            'Lenjani',
            'Lenjani',
          ],
        },
        {
          ward: 'Oldonyowass',
          streets: [
            'Oldonyowass',
            'Oldonyowass',
            'Oldonyowass',
            'Oldonyowass',
            'Losinoni',
            'Losinoni',
            'Losinoni',
            'Engutukoit',
            'Engutukoit',
            'Engutukoit',
            'Engutukoit',
            'Losinoni Juu',
            'Losinoni Juu',
          ],
        },
        {
          ward: 'Laroi',
          streets: [
            'Laroi',
            'Laroi',
            'Laroi',
            'Enjoro',
            'Enjoro',
            'Kisima Cha Mungu',
            'Kisima Cha Mungu',
          ],
        },
        {
          ward: 'Kiutu',
          streets: [
            'Sekei',
            'Sekei',
            'Sekei',
            'Sekei',
            'Sekei',
            'Naurei',
            'Naurei',
            'Naurei',
            'Engorika',
            'Engorika',
            'Engorika',
            'Engorika',
            'Olgilai',
            'Olgilai',
            'Olgilai',
          ],
        },
        {
          ward: 'Tarakwa',
          streets: ['Olgilai', 'Olgilai'],
        },
        {
          ward: 'Ilboru',
          streets: ['Olgilai', 'Olgilai'],
        },
      ],
    },
    {
      district: 'Arumeru',
      wards: [
        {
          ward: 'Usa River',
          streets: [
            'Olgilai',
            'Olgilai',
            'Olgilai',
            'Olgilai',
            'Olgilai',
            'Olgilai',
            'Olgilai',
            'Olgilai',
            'Olgilai',
          ],
        },
        {
          ward: 'Maji Ya Chai',
          streets: [
            'Ngurdoto',
            'Ngurdoto',
            'Ngurdoto',
            'Ngurdoto',
            'Ngurdoto',
            'Kitefu',
            'Kitefu',
            'Kitefu',
            'Kitefu',
            'Kitefu',
            'Maji Ya Chai',
            'Maji Ya Chai',
            'Maji Ya Chai',
            'Lerai',
            'Lerai',
            'Lerai',
            'Ngongongare',
          ],
        },
        {
          ward: 'Nkoaranga',
          streets: ['Nshupu', 'Nshupu', 'Nshupu', 'Nkoaranga', 'Nkoaranga'],
        },
      ],
    },
  ],
};
