import { Region } from '../../../../ngx-mitaa.interfaces';

export const rukwa: Region = {
  region: 'Rukwa',
  districts: [
    {
      district: 'Sumbawanga\r\nCbd',
      wards: [
        {
          ward: 'Sumbawanga',
          streets: [
            'Sumbawanga',
            'Kaswepepe',
            'Mpasi',
            'Yeswe',
            'Kamita',
            'Tambasi',
            'Katuma',
            'Mbalika',
            'Hija',
            'Makutano',
            'Ufipa',
            'Chisicha Mfipa',
            "Wakuung'anga",
            'Isachi',
            'Kasoni',
            'Kiatu',
            'Kimalaunga',
            'Kapufi',
            'Katolile',
            'Momoka',
            'Mtumbuka',
            'Katusa',
            'Ngalu',
          ],
        },
        {
          ward: 'Izia',
          streets: [
            'Halmashauri',
            'Izia',
            'Mtoni',
            'Makaza',
            'Manzitiswe',
            'Shule',
            'Bangwe',
            'Masimba',
            'Kati',
            'Zimamoto',
            'U/ndege',
            'Burudani',
            'Soko',
            'Kaozya',
            'Mbugani',
            'Reginamundi',
            'Yatima',
          ],
        },
        {
          ward: 'Katandala',
          streets: [
            'Katandala ‘c’',
            'Katandala ‘d’',
            'Bomani',
            'Bomani ‘b’',
            'Mbizi ‘c’',
            'Mbizi ‘b’',
            'Comunity Center',
            'Jangwani',
            'Nhc',
            'Sokomatola',
            "Anglikan 'a'",
            "Anglikan 'b'",
            'Mbizi ‘a’',
            "Katandala 'a'",
            "Katandala 'b'",
            'Kasakalawe',
          ],
        },
        {
          ward: 'Malangali',
          streets: [
            'Nyengele',
            'Muhama',
            'Mji Mwema',
            'Isofu',
            'Kilimahewa "a"',
            'Kilimahewa "b"',
            'Katindi',
            'Malangali',
            'Makazi Mapya',
          ],
        },
        {
          ward: 'Kizwite',
          streets: [
            'Senti',
            'Kalangasa',
            'Mbugani',
            'Kawama',
            'Bible',
            'Sokolo',
            'Vuta',
            'Otc',
            'Nantacha',
            'Ndua',
            'Majengo',
            'Kizwite',
            'Trm',
            'Makwasa',
            'Mtumbuka',
          ],
        },
        {
          ward: 'Mazwi',
          streets: [
            'Rtc',
            'Tukuyu',
            'Nhc',
            'Clinic',
            'Lwiche',
            'Msikitini',
            'Kimiti',
            'Chitepo',
            'Lyangalile',
            'Nmc',
            'Zambezi',
            'Viwanda Vidogo',
            'Mashine',
            'Mandela',
            'Karume',
            'Itwelele',
            'Nkasi',
            'Rurecu',
            'Majengo',
          ],
        },
        {
          ward: 'Majengo',
          streets: [
            'Mponda',
            'Namabangasa',
            'Highway',
            'Majengo ‘b’',
            "Bwawani 'a'",
            "Bwawani B'",
            "Majengo  'a'",
            "Majengo  'c'",
            "Majengo  'd'",
            "Mtakuja  'a'",
            "Mtakuja 'b'",
            'Kristu Mfalme',
            'Kaloleni',
            "King'ombe",
          ],
        },
        {
          ward: 'Chanji',
          streets: [
            'Sokodogo',
            'Mianzi',
            'Kawama',
            'Chanji ‘a’',
            'Kichangani',
            'Namteketa',
            'Nankasi',
            'Kati',
            'Bondeni',
            'Bombani',
            'K/mazoezi',
            'Hali Ya Hewa',
            'St Theresia',
            'Vodacom',
            'Mkuyuni',
          ],
        },
        {
          ward: 'Ntendo',
          streets: ['Luwa', 'Ntendo', 'Fyengelezya', 'Kanondo'],
        },
        {
          ward: 'Senga',
          streets: ['Senga', 'Kankwale', 'Wipanga'],
        },
        {
          ward: 'Milanzi',
          streets: ['Mlanda B', 'Milanzi', 'Nambogo'],
        },
        {
          ward: 'Kasense',
          streets: ['Kasense', 'Chipu', 'Mtimbwa'],
        },
        {
          ward: 'Mollo',
          streets: ['Malonje', 'Ulinji', 'Isesa', 'Mawenzusi'],
        },
        {
          ward: 'Matanga',
          streets: ['Matanga', 'Kisumba', 'Chelenganya'],
        },
        {
          ward: 'Pito',
          streets: ['Katumba Azimio', 'Tamasenga', 'Malagano', 'Pito'],
        },
        {
          ward: 'Mafulala',
          streets: [
            'Mafulala',
            'K.k.k.t',
            'Tanesco',
            'Sido',
            'Malechela',
            'Transfoma',
            'Nkana',
            'Kanisa',
            'Jola',
            'Maduka',
            'Momoka',
            'Sekondari',
          ],
        },
        {
          ward: 'Msua',
          streets: [
            'Msua',
            'Maweni',
            'Chemchem',
            'Chemka',
            'King’ombe',
            'Kisiwani',
            'Kilimani',
            'Mzee Nyanya',
            'Shule',
            'Fr. Luka',
            'Kichangani',
            'Malinga',
          ],
        },
        {
          ward: 'Momoka',
          streets: [
            'Kashai',
            'Retco',
            'Edeni  ‘a’',
            'Edeni  ‘b’',
            'Mtakumbuka',
          ],
        },
        {
          ward: 'Lwiche',
          streets: [
            'Utengule',
            'Lwiche',
            'Shengetela',
            'Kaungwa',
            'Majumbasita',
            'Katai',
            'Kafumbusi',
            'Magomeni',
          ],
        },
      ],
    },
    {
      district: 'Sumbawanga',
      wards: [
        {
          ward: 'Laela',
          streets: ['Magomeni'],
        },
        {
          ward: 'Kaengesa',
          streets: ['Kaengesa A', 'Lyapona', 'Mkunda', 'Ltela', 'Kaengesa B'],
        },
        {
          ward: 'Mpui',
          streets: [
            'Mpui A',
            'Ilembo',
            'Ntumbi',
            'Mpui B',
            'Mkima',
            'Kapewa',
            'Mtetezi',
          ],
        },
        {
          ward: 'Sandulula',
          streets: ['Sandulula', 'Mumba', 'Jangwani', 'Kalole'],
        },
        {
          ward: 'Kalambanzite',
          streets: ['Kalambazite', 'Mleche', 'Kilembo', 'Mshani', 'Mlombo'],
        },
        {
          ward: 'Milepa',
          streets: ['Milepa', 'Kinambo', 'Mayenje', 'Kisa', 'Talanda', 'Msia'],
        },
        {
          ward: 'Mtowisa',
          streets: [
            'Mtowisa A',
            'Sontaukia',
            'Mtowisa B',
            "Ng'ongo",
            'Kifinga',
            'Mkamba',
          ],
        },
        {
          ward: 'Muze',
          streets: [
            'Muze',
            'Uzia',
            'Mbwilo',
            'Kizungu',
            'Ilanga',
            'Kalakala',
            'Isangwa',
          ],
        },
        {
          ward: 'Lusaka',
          streets: ['Lusaka', 'Lowe', 'Kizumbi', 'Mpembano'],
        },
        {
          ward: 'Kipeta',
          streets: ['Kipeta', 'Kilyamatundu', 'Legeza', 'Mpona', 'Kirando'],
        },
        {
          ward: 'Kaoze',
          streets: ['Kaoze', 'Tululu', 'Chombe', 'Kiandaigonda'],
        },
        {
          ward: 'Miangalua',
          streets: [
            'Miangalua',
            'Tunko',
            'Movu',
            'Mkowe',
            'Kavifuti',
            'Nampako',
            'Kamsamba',
          ],
        },
        {
          ward: 'Ilemba',
          streets: ['Ilemba A', 'Kaswepa', 'Sakalilo', 'Ilemba B', 'Lyanza'],
        },
        {
          ward: 'Nankanga',
          streets: ['Nankanga', 'Nankanga C', 'Solola'],
        },
        {
          ward: 'Kapenta',
          streets: [
            'Mkusi',
            'Ngomeni',
            'Kawila',
            'Kapenta',
            'Nsanga',
            'Liwelyamvula',
          ],
        },
        {
          ward: 'Kilangawana',
          streets: ['Maleza', 'Kilangawana', 'Mpande', 'Ilambo'],
        },
        {
          ward: 'Zimba',
          streets: ['Zimba', 'Mission', 'Lwanji', 'Kanyala'],
        },
        {
          ward: 'Kalumbaleza',
          streets: [
            'Kalumbaleza A',
            'Kalumbaleza B',
            'Mnazimmoja',
            'Mnazimmoja Asilia',
          ],
        },
        {
          ward: 'Mfinga',
          streets: ['Mfinga', 'Kasekela', 'Msila'],
        },
        {
          ward: 'Mwadui',
          streets: ['Mpete', 'Kipa', 'Nkwilo', 'Katoo', 'Mtapenda', 'Mwadui'],
        },
        {
          ward: 'Ikozi',
          streets: ['Ikozi', 'Kazwila', 'Chituo', 'Tentula'],
        },
        {
          ward: 'Mpwapwa',
          streets: ['Mpwapwa', 'Malolwa', 'Memya', 'Kapoka'],
        },
        {
          ward: 'Lyangalile',
          streets: ['Kianda', 'Kazi', 'Katonto'],
        },
        {
          ward: 'Kanda',
          streets: ['Lula', 'Chitete', 'Lyapona B', 'Lyapona'],
        },
        {
          ward: 'Msanda Muungano',
          streets: [
            'Msandamuungano A',
            'Songambele Azimio',
            'Msandamuungano B',
            'Sikaungu',
          ],
        },
        {
          ward: 'Kasanzama',
          streets: ['Sikaungu'],
        },
        {
          ward: 'Mnokola',
          streets: ['Sikaungu'],
        },
      ],
    },
    {
      district: 'Nkasi',
      wards: [
        {
          ward: 'Namanyere',
          streets: ['Sikaungu'],
        },
        {
          ward: 'Nkomolo',
          streets: ['Sikaungu'],
        },
        {
          ward: 'Isale',
          streets: ['Ntuchi', 'Ntuchi Kusini', 'Kitosi', 'Ifundwa'],
        },
        {
          ward: 'Kipande',
          streets: ['Kipande', 'Nkundi', 'Kantawa', 'Kalundi', 'Nkomolo Ii'],
        },
        {
          ward: 'Chala',
          streets: [
            'Chima',
            'Chala A',
            'Chala C',
            'Chatelekesha',
            'Kacheche',
            'Chala B',
            'Isasa',
            'Londokazi',
          ],
        },
        {
          ward: 'Mtenga',
          streets: ['Londokazi'],
        },
        {
          ward: 'Kabwe',
          streets: [
            'Kabwe',
            'Kabwe Camp',
            'Kanchui',
            'Mpenge',
            'Mkombe',
            'Kalila',
            'Udachi',
          ],
        },
        {
          ward: 'Kirando',
          streets: ['Kamwanda', 'Mpata', 'Mtakuja', 'Kichangani'],
        },
        {
          ward: 'Ninde',
          streets: ['Ninde', 'Namansi', 'Kisambala', 'Kasanga', 'Msamba'],
        },
        {
          ward: 'Kate',
          streets: ['Kate', 'Mwenge', 'Nchenje', 'Ntemba', 'China'],
        },
        {
          ward: 'Sintali',
          streets: ['Sintali', 'Nkana', 'Nkomachindo', 'Kasapa'],
        },
        {
          ward: 'Wampembe',
          streets: ['Wampembe', 'Mwinza', 'Izinga'],
        },
        {
          ward: 'Kala',
          streets: ['Kala', 'Mpasa'],
        },
      ],
    },
    {
      district: 'Kalambo',
      wards: [
        {
          ward: 'Matai',
          streets: ['Matai  Asilia"a"', 'Mikonko', 'Kisungamile', 'Kateka'],
        },
        {
          ward: 'Mkali',
          streets: ['Kizombwe', 'Kalalasi', 'Myunga', 'Mpanzi'],
        },
        {
          ward: 'Mnamba',
          streets: ['Mnamba', 'Kantalemwa', 'Luse', 'Mtula', 'Msipazi'],
        },
        {
          ward: 'Msanzi',
          streets: ['Msanzi', 'Kambiala', 'Nachula', 'Katuka'],
        },
        {
          ward: 'Mkowe',
          streets: ['Mkowe', 'Mbuza', 'Katapulo', 'Sengakalonje', 'Ilimba'],
        },
        {
          ward: 'Kasanga',
          streets: ['Muzi', 'Kasanga', 'Kapele', 'Kilewani', 'Kipwa'],
        },
        {
          ward: 'Katazi',
          streets: ['Katazi', 'Ninga', 'Mwaya', 'Mvula'],
        },
        {
          ward: 'Mwazye',
          streets: ['Kazila', 'Mpenje', 'Msoma', 'Mwazye'],
        },
        {
          ward: 'Ulumi',
          streets: [
            'Ulumi "a"',
            "Ulumi ''b''",
            'Mnazi',
            'Kale',
            'Kalepula "a"',
            'Kalepula "b"',
          ],
        },
        {
          ward: 'Samazi',
          streets: ['Kipanga', 'Katili', 'Samazi', 'Kisala'],
        },
        {
          ward: 'Mpombwe',
          streets: ['Mpombwe', 'Mpombwe "b"', 'Kapozwa', 'Kalambo', 'Ngorotwa'],
        },
      ],
    },
  ],
};
