import { Region } from '../../../../ngx-mitaa.interfaces';

export const iringa: Region = {
  region: 'Iringa',
  districts: [
    {
      district: 'Iringa Cbd',
      wards: [
        {
          ward: 'Mivinjeni',
          streets: [
            'Migombani',
            'Idunda',
            "Frelimo 'a'",
            'Darajani',
            'Kondoa',
            'Kanisani',
            'Mjimwema',
          ],
        },
        {
          ward: 'Mshindo',
          streets: [
            "Mshindo 'a'",
            "Mshindo 'b'",
            'Benki',
            'Msikiti',
            'Ruaha',
            "Mtwa 'a'",
            "Mtwa 'b'",
          ],
        },
        {
          ward: 'Kitanzini',
          streets: [
            'Stendi Kuu',
            'Miyomboni',
            'Jamat',
            'Maweni',
            'Legezamwendo',
            'Madrasa',
            'Kitanzini',
            'Mlimani',
            'Polisi Line',
          ],
        },
        {
          ward: 'Makorongoni',
          streets: [
            'Msichoke',
            'Mkwawa Road',
            'Kaguo',
            'Sekondari',
            'Pangani',
            'Kibwana',
            'Mahiwa',
            'Pawaga Road',
            'Tandamti',
            'Baniani',
            'Mahagi',
            'Muhimba "a"',
            'Muhimba "b"',
          ],
        },
        {
          ward: 'Ilala',
          streets: [
            'Mlamke',
            'Nyumba Tatu',
            'Embakasi',
            'Lami A',
            'Lami B',
            'Dabobado',
            'Kajificheni',
          ],
        },
        {
          ward: 'Kwakilosa',
          streets: [
            "Frelimo 'c'",
            "Muungano 'b'",
            'Shule',
            'Kijiweni',
            'Kidunda',
            'Jangwani',
            'Samora',
            'Beira',
            "Muungano 'a'",
            'Kisiwani',
          ],
        },
        {
          ward: 'Mlandege',
          streets: [
            'Ngulika',
            'Msanya',
            'Mafuruto',
            'Sokoni',
            'Mlambalazi',
            'Nguzo',
            'Makondeko',
            'Lubida',
            'Kalenga Road',
            'Kota',
            'Mapinduzi',
            "Ngeng'ena",
          ],
        },
        {
          ward: 'Gangilonga',
          streets: [
            'Kinondoni',
            'Kichangani',
            'Ffu',
            'Lugalo A',
            'Lugalo B',
            'Wilolesi',
            'Sabasaba',
            'Gangilonga',
            'Kilimani',
          ],
        },
        {
          ward: 'Kihesa',
          streets: [
            'Dodoma Road A',
            'Dodoma Road B',
            "Semtema 'a'",
            "Semtema 'b'",
            'Ilembula',
            'Mwenge',
            'Mafifi',
            'Kilimani',
            'Ngome',
            "Dodoma Road 'f'",
            'Sokoni',
            'Mfaranyaki',
            'Ramadhani Waziri',
            'Msikitini',
            'Mbuma',
          ],
        },
        {
          ward: 'Mtwivila',
          streets: [
            'Semkini',
            "Mtwivila 'a'",
            "Mtwivila 'b'",
            'Mtwivila "c"',
            'Viziwi',
            'Mwautwa',
            'Dodoma Road "c"',
            'Dodoma Road "d"',
            'Idunda',
            'Dodoma Road "e"',
          ],
        },
        {
          ward: 'Mkwawa',
          streets: [
            'Lukosi',
            'Imalanongwa A',
            'Imalanongwa B',
            'Bwawani "a"',
            "Bwawani 'b'",
            "Wazo 'a'",
            "Wazo 'b'",
            'Mkwawa Chuo',
            "Don Bosco 'a'",
            "Don Bosco 'b'",
            'Mgera',
            'Itamba',
            'Hoho',
            "Ikonongo 'a'",
            "Ikonongo 'b'",
          ],
        },
        {
          ward: 'Mwangata',
          streets: [
            'Kigamboni',
            'Kisiwani',
            'Mawelewele',
            'Ngelewala',
            "Isoka 'a'",
            "Isoka 'b'",
            "Mwangata 'a'",
            "Mwangata 'b'",
            "Mwangata 'c'",
            "Mwangata 'd'",
            'Muungano',
          ],
        },
        {
          ward: 'Kitwiru',
          streets: [
            "Kibwabwa 'a'",
            "Kibwabwa 'b'",
            "Nyamhanga 'a'",
            "Nyamhanga 'b'",
            "Nyamhanga 'c'",
            'Kisiwani',
            "Nyamhanga 'd'",
            "Nyamhanga 'e'",
            'Cagliero',
            'Mosi',
            "Uyole 'a'",
            "Uyole 'b'",
            "Kitwiru 'a'",
            "Kitwiru 'b'",
          ],
        },
        {
          ward: 'Ruaha',
          streets: [
            "Ipogolo 'a'",
            "Ipogolo 'b'",
            "Ipogolo 'c'",
            'Tagamenda',
            "Ipogolo 'd'",
            'Mwagongo',
            "Ipogolo 'e'",
            'Ngeleli',
            'Buguruni',
            "Kinegamgosi 'a'",
            'Chuo',
            "Kinegamgosi 'b'",
            "Kinegamgosi 'c'",
          ],
        },
        {
          ward: 'Nduli',
          streets: [
            'Mapanda',
            'Mji Mwema',
            'Kilimahewa',
            'Kisowele',
            'Kipululu',
            'Njia Panda',
            'Mtalagala',
            'Msisina',
            'Mibata',
            'Igungandembwe',
            'Sombeli',
          ],
        },
        {
          ward: 'Isakalilo',
          streets: [
            'Isakalilo',
            "Kihodombi 'a'",
            "Kihodombi 'b'",
            'Kitasengwa',
            'Njia Panda',
            'Zizi',
            'Mtwivila',
            'Chautinde',
            'Kisaula',
          ],
        },
        {
          ward: 'Mkimbizi',
          streets: [
            'Dodoma Road Trm',
            'Mkimbizi "a"',
            'Kaduma',
            'Mkimbizi "b"',
            'Mkimbizi "c"',
            'Mkimbizi "d"',
            'Kihesa Kilolo "a"',
            'Kihesa Kilolo "b"',
            'Ugele Ilangila',
            'Ugele  Manyigi',
          ],
        },
        {
          ward: 'Igumbilo',
          streets: [
            "Ndiuka 'a'",
            "Ndiuka 'b'",
            "Ndiuka 'c'",
            "Ndiuka 'd'",
            "Ndiuka 'e'",
            'Mlangali',
            'Igumbilo',
            'Matungulu',
            'Kigungawe A',
            'Kigungawe B',
          ],
        },
      ],
    },
    {
      district: 'Iringa',
      wards: [
        {
          ward: 'Kalenga',
          streets: ['Tosamaganga', 'Kalenga', 'Isakalilo'],
        },
        {
          ward: 'Maguliwa',
          streets: [
            'Magulilwa',
            'Ng’enza',
            'Msuluti',
            'Mlanda',
            'Negabihi',
            'Ndiwili',
          ],
        },
        {
          ward: 'Mgama',
          streets: [
            'Ibumila',
            'Lwato',
            'Ilandutwa',
            'Mgama',
            'Itwaga',
            'Ihemi',
          ],
        },
        {
          ward: 'Mseke',
          streets: ['Tanangozi', 'Mlandege', 'Ugwachanya', 'Wenda'],
        },
        {
          ward: 'Ulanda',
          streets: [
            'Mangalali',
            'Kibebe',
            'Lupalama',
            'Ibangamoyo',
            'Mwambao',
            'Weru',
          ],
        },
        {
          ward: 'Nzihi',
          streets: [
            'Nyamihuu',
            'Kipera',
            'Magubike',
            'Nzihi',
            'Ilalasimba',
            'Kidamali',
          ],
        },
        {
          ward: 'Kiwere',
          streets: ['Kiwere', 'Mgera', 'Itagutwa', 'Kitapilimwa', 'Mfyome'],
        },
        {
          ward: 'Mlowa',
          streets: ['Malizanga', 'Nyamahana', 'Mafuluto'],
        },
        {
          ward: 'Ilolompya',
          streets: ['Luganga', 'Magozi', 'Mkombilenga', 'Ilolompya'],
        },
        {
          ward: 'Kihorogota',
          streets: [
            'Kihorogota',
            'Ivangwa',
            'Ngano',
            "Mikong'wi",
            'Ismani (t)',
            'Ndolela',
            'Uhominyi',
            'Igula',
          ],
        },
        {
          ward: 'Lumuli',
          streets: ['Lumuli', 'Itengulinyi', 'Isupilo', 'Muwimbi'],
        },
        {
          ward: 'Ifunda',
          streets: [
            'Ifunda',
            'Bandabichi',
            'Kibena',
            'Mfukulembe',
            'Udumka',
            'Mibikimitali',
          ],
        },
        {
          ward: 'Maboga',
          streets: ['Magunga', 'Makongati', 'Kiponzelo'],
        },
        {
          ward: 'Wasa',
          streets: [
            'Wasa',
            'Ikungwe',
            'Ufyambe',
            'Usengelindete',
            'Ihomasa',
            'Ulata',
            'Mahanzi',
          ],
        },
        {
          ward: 'Mahuninga',
          streets: ['Mahuninga', 'Kisilwa', 'Makifu'],
        },
        {
          ward: 'Itunundu',
          streets: ['Itunundu', 'Kimande', 'Mbuyuni'],
        },
        {
          ward: 'Izazi',
          streets: ['Makuka', 'Izazi', 'Mnadani'],
        },
        {
          ward: 'Malengamakali',
          streets: [
            'Nyakavangala',
            'Isaka',
            'Makadupa',
            'Iguluba',
            'Mkulula',
            'Usolanga',
          ],
        },
        {
          ward: 'Idodi',
          streets: ['Idodi', 'Mapogoro', 'Kitisi', 'Tungamalenga'],
        },
        {
          ward: "Nyang'oro",
          streets: [
            'Nyang’oro',
            'Chamndindi',
            'Holo',
            'Mawindi',
            'Ikengeza',
            'Mangawe',
          ],
        },
        {
          ward: 'Migoli',
          streets: [
            'Migoli',
            'Mtera',
            'Makatapola',
            'Mbweleli',
            'Kinyali',
            'Maperamengi',
          ],
        },
        {
          ward: "Kising'a",
          streets: [
            'Ilambilole',
            'Matembo',
            'Mkungugu',
            'Kinywang’anga',
            'Igingilanyi',
            'Kising’a Ismani',
          ],
        },
        {
          ward: 'Mlenge',
          streets: ['Kisanga', 'Magombwe', 'Kinyika', 'Isele Pawaga'],
        },
        {
          ward: 'Lyamgungwe',
          streets: [
            'Lupembelwasenga',
            'Kikombwe',
            'Igunda',
            'Malagosi',
            'Lyamgungwe',
          ],
        },
        {
          ward: 'Luhota',
          streets: ['Tagamenda', 'Kilambo', 'Nyabula', 'Ikuvilo', 'Wangama'],
        },
        {
          ward: 'Kihanga',
          streets: ['Makombe', 'Kihanga', 'Kidilo', "Igangidung'u", 'Chamgogo'],
        },
        {
          ward: 'Masaka',
          streets: ["Kaning'ombe", 'Sadani', 'Makota'],
        },
        {
          ward: 'Mboliboli',
          streets: ['Mboliboli', 'Mbugani', 'Mkumbwanyi'],
        },
      ],
    },
    {
      district: 'Kilolo',
      wards: [
        {
          ward: 'Irole',
          streets: ['Irole', 'Lundamatwe', 'Kitumbuka', 'Mawala'],
        },
      ],
    },
  ],
};
